name: alb-pathbased

#on:
#  push:
#    branches:
#      - master
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  terraform:
    name: Terraform Operations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125784755:role/OIDC-auth-GA
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ">= 1.12.0"
            
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./

      - name: Validating Terraform
        run: terraform validate
        working-directory: ./

      - name: Checking terraform plan for dry-run
        run: terraform plan
        working-directory: ./
        
      - name: Infra provision with terraform apply
        run: terraform apply -auto-approve
        working-directory: ./
        
      - name: Destroying infra
        run: terraform destroy -auto-approve
        working-directory: ./
