name: alb-pathbased

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Operations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./

      - name: Validating Terraform
        run: terraform validate
        working-directory: ./
